# Generated by Django 4.0.5 on 2022-07-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0002_customer_id_alter_customer_fleet_categorization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='id',
            new_name='company_id',
        ),
    ]
