# Generated by Django 4.0.5 on 2022-07-10 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0003_rename_id_customer_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='BU',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ISV_fleet_BU_Input',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='addressibility',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='addressibility_calc',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='business_vertical',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='fleet_categorization',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='served_unserved',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='unit',
        ),
        migrations.CreateModel(
            name='CustomerInformation',
            fields=[
                ('info_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('addressibility', models.CharField(choices=[('Addressable', 'Addressable'), ('Unaddressable', 'Unaddressable'), ('Not-Applicable', 'Not-Applicable')], max_length=20)),
                ('addressibility_calc', models.CharField(choices=[('Addressable', 'Addressable'), ('Unaddressable', 'Unaddressable'), ('Not-Applicable', 'Not-Applicable')], max_length=20)),
                ('served_unserved', models.CharField(choices=[('Served', 'Served'), ('Unserved', 'Unserved')], max_length=20)),
                ('BU', models.CharField(choices=[('ISV', 'ISV'), ('GSV', 'GSV')], max_length=30)),
                ('unit', models.CharField(max_length=100, null=True)),
                ('business_vertical', models.CharField(max_length=200, null=True)),
                ('fleet_categorization', models.CharField(choices=[('ISV-In UDI-Not in SFDC', 'ISV-In UDI-Not in SFDC'), ('ISV-In SFDC-In UDI-Retain', 'ISV-In SFDC-In UDI-Retain'), ('GSV-Matching with SFDC', 'GSV-Matching with SFDC'), ('GSV-Not in SFDCs', 'GSV-Not in SFDCs'), ('GSV-Not in UDI', 'GSV-Not in UDI')], max_length=400)),
                ('ISV_fleet_BU_Input', models.IntegerField(null=True)),
                ('company', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='Invent.customer')),
            ],
        ),
    ]
