# Generated by Django 4.0.5 on 2022-07-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0004_remove_customer_bu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinformation',
            name='info_id',
        ),
        migrations.AddField(
            model_name='customerinformation',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
