# Generated by Django 4.0.5 on 2022-07-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0005_remove_customerinformation_info_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.IntegerField(unique=True),
        ),
    ]
