# Generated by Django 4.0.5 on 2022-07-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0007_remove_allottask_id_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='manager_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
