# Generated by Django 4.0.6 on 2022-07-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0008_employee_manager_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cr_status',
            field=models.CharField(choices=[('Conversion', 'Conversion'), ('Retention', 'Retention')], default=None, max_length=100, null=True),
        ),
    ]
