# Generated by Django 4.0.6 on 2022-07-26 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0013_alter_businesspotential_addresable_market_inr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allottask',
            name='company',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='Invent.customer'),
        ),
        migrations.AlterField(
            model_name='businesspotential',
            name='OEM_oOEM',
            field=models.CharField(choices=[('OEM', 'OEM'), ('oOEM', 'oOEM')], default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_id',
            field=models.IntegerField(default='None'),
        ),
    ]
